[package]
name = "image_test"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
opencv = "0.93.3"
# opencv = { version = "0.93.3", default-features = false, features = ["videoio", "video", "highgui", "imgproc"] }
